language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
notifications:
  email: true
node_js:
  - '10'
script:
  - npm run cy:run
# after_success:
#   - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
